//go:generate ./generrno.py
// Code generated by generrno.py. DO NOT EDIT.

package llamacppcgo

type ErrorCode int

const (
	LCC_ERROR_SUCCESS                         ErrorCode = 0
	LCC_ERROR_NOT_IMPLEMENTED                 ErrorCode = -1
	LCC_ERROR_UNKNOWN                         ErrorCode = -2
	LCC_ERROR_FAILED_ALLOCATE_MEMORY          ErrorCode = -3
	LCC_ERROR_INVALID_ARGUMENT                ErrorCode = -4
	LCC_ERROR_FAILED_LOAD_MODEL               ErrorCode = -5
	LCC_ERROR_FAILED_CREATE_CONTEXT           ErrorCode = -6
	LCC_ERROR_FAILED_CREATE_MTMD_CONTEXT      ErrorCode = -7
	LCC_ERROR_FAILED_CREATE_SAMPLER           ErrorCode = -8
	LCC_ERROR_FAILED_LOAD_LIBRARY             ErrorCode = -9
	LCC_ERROR_FAILED_LOAD_SYMBOL              ErrorCode = -10
	LCC_ERROR_FAILED_CREATE_MTMD_INPUT_CHUNKS ErrorCode = -11
	LCC_ERROR_FAILED_MTMD_TOKENIZE            ErrorCode = -12
	LCC_ERROR_FAILED_MTMD_EVAL                ErrorCode = -13
	LCC_ERROR_FAILED_SAMPLE                   ErrorCode = -14
	LCC_ERROR_FAILED_CREATE_AUDIO_BITMAP      ErrorCode = -15
	LCC_ERROR_FAILED_LLM_DECODE               ErrorCode = -16
	LCC_ERROR_FAILED_TOKENIZE                 ErrorCode = -17
)

func (e ErrorCode) Error() string {
	switch e {
	case LCC_ERROR_SUCCESS:
		return "success"
	case LCC_ERROR_NOT_IMPLEMENTED:
		return "not implemented"
	case LCC_ERROR_UNKNOWN:
		return "unknown error"
	case LCC_ERROR_FAILED_ALLOCATE_MEMORY:
		return "failed to allocate memory"
	case LCC_ERROR_INVALID_ARGUMENT:
		return "invalid argument"
	case LCC_ERROR_FAILED_LOAD_MODEL:
		return "failed to load model"
	case LCC_ERROR_FAILED_CREATE_CONTEXT:
		return "failed to create llama.cpp context"
	case LCC_ERROR_FAILED_CREATE_MTMD_CONTEXT:
		return "failed to create MTMD context"
	case LCC_ERROR_FAILED_CREATE_SAMPLER:
		return "failed to create sampler"
	case LCC_ERROR_FAILED_LOAD_LIBRARY:
		return "failed to load library"
	case LCC_ERROR_FAILED_LOAD_SYMBOL:
		return "failed to load symbol"
	case LCC_ERROR_FAILED_CREATE_MTMD_INPUT_CHUNKS:
		return "failed to create MTMD input chunks"
	case LCC_ERROR_FAILED_MTMD_TOKENIZE:
		return "failed to tokenize input with MTMD"
	case LCC_ERROR_FAILED_MTMD_EVAL:
		return "failed to eval input with MTMD"
	case LCC_ERROR_FAILED_SAMPLE:
		return "failed to sample token"
	case LCC_ERROR_FAILED_CREATE_AUDIO_BITMAP:
		return "failed to create MTMD audio bitmap"
	case LCC_ERROR_FAILED_LLM_DECODE:
		return "failed to do LLM decode"
	case LCC_ERROR_FAILED_TOKENIZE:
		return "failed to tokenize text"
	default:
		return "unknown error"
	}
}
