#!/usr/bin/env python3
#-*- coding: utf-8 -*-

import os
import re
import subprocess

def mian():
    scriptDir = os.path.dirname(os.path.abspath(__file__))

    enumStartRe = re.compile(r"typedef\s+enum\s+_LCCErrorCode\s*\{")
    enumEndRe = re.compile(r"\}\s*LCCErrorCode\s*;")
    itemRe = re.compile(r"\s*(\w+)\s*=\s*(-?\d+)\s*,\s*//\s*\"([^\"]+)\"")

    errCodes = []

    with open(os.path.join(scriptDir, "wrapper.h"), "r", encoding="utf-8") as fi:
        inEnum = False
        for line in fi:
            if enumStartRe.match(line):
                inEnum = True
                continue
            if enumEndRe.match(line):
                inEnum = False
                continue
            if inEnum:
                m = itemRe.match(line)
                if m:
                    name, code, msg = m.groups()
                    errCodes.append((name, int(code), msg))

        # print(errCodes)

        with open(os.path.join(scriptDir, "errno.go"), "w", encoding="utf-8") as fo:
            fo.write("//go:generate ./generrno.py\n")
            fo.write("// Code generated by generrno.py from wrapper.h. DO NOT EDIT.\n\n")

            fo.write("package llamacppcgo\n\n")

            fo.write("type ErrorCode int\n\n")

            fo.write("const (\n")
            for name, code, msg in errCodes:
                fo.write(f"\t{name} ErrorCode = {code}\n")
            fo.write(")\n\n")

            fo.write("func (e ErrorCode) Error() string {\n")
            fo.write("\tswitch e {\n")
            for name, code, msg in errCodes:
                fo.write(f"\tcase {name}:\n")
                fo.write(f"\t\treturn \"{msg}\"\n")
            fo.write("\tdefault:\n")
            fo.write("\t\treturn \"unknown error\"\n")
            fo.write("\t}\n")
            fo.write("}\n")
        
    subprocess.run(["gofmt", "-w", os.path.join(scriptDir, "errno.go")], check=True)

if __name__ == "__main__":
    mian()

