// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "do health check, return 200 if the server is healthy, otherwise return 500",
                "produces": [
                    "application/json"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/cpullmapi.HealthcheckResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        },
        "/matting": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "matting image, output image format is determined by the Accept header, if accept is not set, use the input image format",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/bmp",
                    "image/gif",
                    "image/webp",
                    "image/tiff",
                    "image/jp2",
                    "image/jxl",
                    "image/heif"
                ],
                "summary": "matting image",
                "parameters": [
                    {
                        "enum": [
                            "image/jpeg",
                            "image/png",
                            "image/bmp",
                            "image/gif",
                            "image/webp",
                            "image/tiff",
                            "image/jp2",
                            "image/jxl",
                            "image/heif"
                        ],
                        "type": "string",
                        "description": "input image format, if not set, auto detect from image data",
                        "name": "Content-Type",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "model name, for example: MVANet",
                        "name": "X-Model",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image data in binary, conflicts with imageURL",
                        "name": "imageData",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "image url, conflicts with imageData",
                        "name": "imageURL",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "background color in rgba hex format, for example: #ffffffff, default is #ffffff for white",
                        "name": "backgroundColor",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image data in binary",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "cpullmapi.HTTPCode": {
            "type": "integer",
            "enum": [
                200,
                404,
                401,
                403,
                500
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeNotFound",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeInternalServerError"
            ]
        },
        "cpullmapi.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean",
                    "example": true
                },
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/cpullmapi.HTTPCode"
                        }
                    ],
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "Token": {
            "description": "\"Type 'Token TOKEN' to correctly set the API Key\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
