// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "do health check, return 200 if the server is healthy, otherwise return 500",
                "produces": [
                    "application/json"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/cpullmapi.HealthcheckResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        },
        "/matting": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "matting image, output image format is determined by the Accept header, if accept is not set, use the input image format",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/bmp",
                    "image/gif",
                    "image/webp",
                    "image/tiff",
                    "image/jp2",
                    "image/jxl"
                ],
                "summary": "matting image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model name, for example: MVANet",
                        "name": "modelName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image data in binary, conflicts with imageURL",
                        "name": "imageData",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "image url, conflicts with imageData",
                        "name": "imageURL",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "background color in rgba hex format, for example: #ffffffff, default is #ffffff00 for white",
                        "name": "backgroundColor",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "image data in binary",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        },
        "/transcribe": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "transcribe audio, output text and language,",
                "produces": [
                    "application/json"
                ],
                "summary": "transcribe audio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model name, for example: FireRedASR",
                        "name": "modelName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "down mix method, for example: average(default), left, right",
                        "name": "downMixMethod",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "hotwords, separated by comma",
                        "name": "hotwords",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "audio data in WAVE format, conflicts with audioURL",
                        "name": "audioData",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "audio url, conflicts with audioData",
                        "name": "audioURL",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ASR result",
                        "schema": {
                            "$ref": "#/definitions/cpullmapi.ASRResult"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    },
                    "500": {
                        "description": "internal server error"
                    }
                }
            }
        },
        "/transcribe/realtime": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Transcribe raw signed 16-bit little-endian PCM sent as binary frames.\n\nThe token may be sent either as an \"Authorization: Token \u003ctoken\u003e\" header or, for browsers which cannot set headers on a websocket, in the handshake as \"Sec-WebSocket-Protocol: realtime, openai-insecure-api-key.\u003ctoken\u003e\".\n\nAfter the handshake the client may send one optional text frame {\"type\":\"session.update\",\"hotwords\":\"...\"}, then binary PCM frames, and finally {\"type\":\"input_audio_buffer.commit\"} to end the audio. The server answers with text frames {\"type\":\"transcript\",...}, each carrying the full transcript so far.",
                "produces": [
                    "application/json"
                ],
                "summary": "transcribe audio as a stream over websocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model name, for example: LCCStreamingASR",
                        "name": "modelName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "switching protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    }
                }
            }
        },
        "/transcribe/stream": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Transcribe raw signed 16-bit little-endian PCM, streamed in the request body.\n\nPCM parameters are passed in the Content-Type and the query string rather than as multipart form fields, because streaming has to start handing audio to the model before the body ends and multipart would buffer it first.\n\nThe response is a text/event-stream: one \"data: {...}\" per ASRStreamResult, terminated by \"data: [DONE]\". Each result carries the full transcript so far, not a delta. Clients must use fetch with a ReadableStream, since EventSource cannot send a request body.",
                "consumes": [
                    "audio/L16"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "summary": "transcribe audio as a stream over server-sent events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model name, for example: LCCStreamingASR",
                        "name": "modelName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "hotwords, separated by comma",
                        "name": "hotwords",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "override the r trim tokens configured for the model",
                        "name": "rTrimTokens",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "one event per result, then data: [DONE]",
                        "schema": {
                            "$ref": "#/definitions/cpullmapi.ASRStreamResult"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "401": {
                        "description": "unauthorized"
                    }
                }
            }
        }
    },
    "definitions": {
        "cpullmapi.ASRResult": {
            "type": "object",
            "properties": {
                "emotion": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cpullmapi.ASRStreamResult": {
            "type": "object",
            "properties": {
                "counter": {
                    "type": "integer"
                },
                "endOfUtterance": {
                    "type": "boolean"
                },
                "final": {
                    "type": "boolean"
                },
                "lang": {
                    "type": "string"
                },
                "t0": {
                    "type": "number"
                },
                "t1": {
                    "type": "number"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cpullmapi.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "authorized": {
                    "type": "boolean",
                    "example": true
                },
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "Token": {
            "description": "\"Type 'Token TOKEN' to correctly set the API Key\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
